import { TaskStatus, ITaskStatus } from './task-status.model';
import Task from '../tasks/task.model';
import AppError from '../../shared/utils/appError';

export class TaskStatusService {
  /**
   * Get all statuses for a workspace (ordered)
   */
  async getByWorkspace(workspaceId: string): Promise<ITaskStatus[]> {
    return TaskStatus.find({ workspaceId }).sort({ order: 1 });
  }

  /**
   * Create a new status
   */
  async create(
    workspaceId: string,
    data: { name: string; color: string; icon?: string; category: string; isDefault?: boolean },
    userId: string
  ): Promise<ITaskStatus> {
    // Get next order number
    const lastStatus = await TaskStatus.findOne({ workspaceId }).sort({ order: -1 });
    const order = lastStatus ? lastStatus.order + 1 : 0;

    // If setting as default, unset current default
    if (data.isDefault) {
      await TaskStatus.updateMany({ workspaceId, isDefault: true }, { isDefault: false });
    }

    const status = await TaskStatus.create({
      workspaceId,
      name: data.name,
      slug: '', // Auto-generated by pre-save hook
      color: data.color,
      icon: data.icon || 'circle',
      category: data.category,
      order,
      isDefault: data.isDefault || false,
      createdBy: userId,
    });

    return status;
  }

  /**
   * Update a status
   */
  async update(
    statusId: string,
    workspaceId: string,
    data: { name?: string; color?: string; icon?: string; category?: string; isDefault?: boolean },
    userId: string
  ): Promise<ITaskStatus> {
    const status = await TaskStatus.findOne({ _id: statusId, workspaceId });
    if (!status) {
      throw new AppError('Status not found.', 404);
    }

    if (data.name !== undefined) status.name = data.name;
    if (data.color !== undefined) status.color = data.color;
    if (data.icon !== undefined) status.icon = data.icon;
    if (data.category !== undefined) status.category = data.category as any;

    // Handle default toggle
    if (data.isDefault === true) {
      await TaskStatus.updateMany({ workspaceId, isDefault: true }, { isDefault: false });
      status.isDefault = true;
    } else if (data.isDefault === false) {
      status.isDefault = false;
    }

    status.updatedBy = userId as any;
    await status.save();

    return status;
  }

  /**
   * Delete a status (only if no tasks use it)
   */
  async delete(statusId: string, workspaceId: string, userId: string): Promise<void> {
    const status = await TaskStatus.findOne({ _id: statusId, workspaceId });
    if (!status) {
      throw new AppError('Status not found.', 404);
    }

    // Check if any tasks use this status
    const taskCount = await Task.countDocuments({ status: status.slug, workspaceId });
    if (taskCount > 0) {
      throw new AppError(
        `Cannot delete status "${status.name}". ${taskCount} task(s) are currently using it. Reassign them first.`,
        400
      );
    }

    await status.softDelete(userId);
  }

  /**
   * Reorder statuses
   */
  async reorder(workspaceId: string, orderedIds: string[]): Promise<ITaskStatus[]> {
    const bulkOps = orderedIds.map((id, index) => ({
      updateOne: {
        filter: { _id: id, workspaceId },
        update: { $set: { order: index } },
      },
    }));

    await TaskStatus.bulkWrite(bulkOps);

    return TaskStatus.find({ workspaceId }).sort({ order: 1 });
  }
}

export const taskStatusService = new TaskStatusService();
export default TaskStatusService;
