import { TaskPriority, ITaskPriority } from './task-priority.model';
import Task from '../tasks/task.model';
import AppError from '../../shared/utils/appError';

export class TaskPriorityService {
  /**
   * Get all priorities for a workspace (ordered)
   */
  async getByWorkspace(workspaceId: string): Promise<ITaskPriority[]> {
    return TaskPriority.find({ workspaceId }).sort({ order: 1 });
  }

  /**
   * Create a new priority
   */
  async create(
    workspaceId: string,
    data: { name: string; color: string; icon: string; isDefault?: boolean },
    userId: string
  ): Promise<ITaskPriority> {
    // Get next order number
    const lastPriority = await TaskPriority.findOne({ workspaceId }).sort({ order: -1 });
    const order = lastPriority ? lastPriority.order + 1 : 0;

    // If setting as default, unset current default
    if (data.isDefault) {
      await TaskPriority.updateMany({ workspaceId, isDefault: true }, { isDefault: false });
    }

    const priority = await TaskPriority.create({
      workspaceId,
      name: data.name,
      slug: '', // Auto-generated by pre-save hook
      color: data.color,
      icon: data.icon,
      order,
      isDefault: data.isDefault || false,
      createdBy: userId,
    });

    return priority;
  }

  /**
   * Update a priority
   */
  async update(
    priorityId: string,
    workspaceId: string,
    data: { name?: string; color?: string; icon?: string; isDefault?: boolean },
    userId: string
  ): Promise<ITaskPriority> {
    const priority = await TaskPriority.findOne({ _id: priorityId, workspaceId });
    if (!priority) {
      throw new AppError('Priority not found.', 404);
    }

    if (data.name !== undefined) priority.name = data.name;
    if (data.color !== undefined) priority.color = data.color;
    if (data.icon !== undefined) priority.icon = data.icon;

    // Handle default toggle
    if (data.isDefault === true) {
      await TaskPriority.updateMany({ workspaceId, isDefault: true }, { isDefault: false });
      priority.isDefault = true;
    } else if (data.isDefault === false) {
      priority.isDefault = false;
    }

    priority.updatedBy = userId as any;
    await priority.save();

    return priority;
  }

  /**
   * Delete a priority (only if no tasks use it)
   */
  async delete(priorityId: string, workspaceId: string, userId: string): Promise<void> {
    const priority = await TaskPriority.findOne({ _id: priorityId, workspaceId });
    if (!priority) {
      throw new AppError('Priority not found.', 404);
    }

    // Check if any tasks use this priority
    const taskCount = await Task.countDocuments({ priority: priority.slug, workspaceId });
    if (taskCount > 0) {
      throw new AppError(
        `Cannot delete priority "${priority.name}". ${taskCount} task(s) are currently using it. Reassign them first.`,
        400
      );
    }

    await priority.softDelete(userId);
  }

  /**
   * Reorder priorities
   */
  async reorder(workspaceId: string, orderedIds: string[]): Promise<ITaskPriority[]> {
    const bulkOps = orderedIds.map((id, index) => ({
      updateOne: {
        filter: { _id: id, workspaceId },
        update: { $set: { order: index } },
      },
    }));

    await TaskPriority.bulkWrite(bulkOps);

    return TaskPriority.find({ workspaceId }).sort({ order: 1 });
  }
}

export const taskPriorityService = new TaskPriorityService();
export default TaskPriorityService;
